FROM node:12.14.1-slim as dev
ENV NODE_ENV=development
ENV PORT=8080

WORKDIR /app
COPY package*.json ./

# installing bcrypt manually so that proper binaries are created for the container
# RUN npm install -g typescript && npm install && npm install bcrypt && npm cache clean --force
RUN npm install && npm cache clean --force
COPY . .
RUN npm run tsc
CMD npm start